//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.20 at 08:50:51 AM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.009.001.12", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.MT_MX.demo.iso20022.pacs_009_001_12;


