spring.application.name=demo
dd=C:\\Users\\Abhishek\\Downloads\\demo (3)\\demo\\src\\main\\resources\\application1.properties

swift.cbpr.msgDefIdr.pacs008= pacs.008.001.13
swift.cbpr.msgDefIdr.pacs009=pacs.009.001.12
swift.cbpr.bizSvc: swift.cbprplus.02

spring.datasource.url=jdbc:postgresql://localhost:5432/Transaction
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8081