//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.19 at 08:39:32 AM IST 
//


package com.MT_MX.demo.iso20022.pacs;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CryptographicKey1Choice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CryptographicKey1Choice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ILPV4" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.13}HexBinaryText"/>
 *         &lt;element name="Sgntr" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.13}SHA256SignatureText"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CryptographicKey1Choice", propOrder = {
    "ilpv4",
    "sgntr"
})
public class CryptographicKey1Choice {

    @XmlElement(name = "ILPV4")
    protected String ilpv4;
    @XmlElement(name = "Sgntr")
    protected String sgntr;

    /**
     * Gets the value of the ilpv4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getILPV4() {
        return ilpv4;
    }

    /**
     * Sets the value of the ilpv4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setILPV4(String value) {
        this.ilpv4 = value;
    }

    /**
     * Gets the value of the sgntr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSgntr() {
        return sgntr;
    }

    /**
     * Sets the value of the sgntr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSgntr(String value) {
        this.sgntr = value;
    }

}




